/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      versionmacro.cpp                           ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
//#ifndef SET_VERSION_STRING
//#define SET_VERSION_STRING 50801
//#endif

#define SET_VERSION_STRING "5.8.0.1"
#include "versionmacro.h"
#include <stdio.h>

ulong data[2] = {0,0};
char* vers = (char*)&data[0];

LongCCValue versionstring(void)
{
#ifdef string_string 
    LongCCValue lcc;
    lcc.number = *(const ulong*)VERSION_STRING;
#elif defined(number_number)
    LongCCValue lcc;
    lcc.number = VERSION_STRING;
#else
    LongCCValue lcc = VERSION_STRING;
#endif
    return lcc;
}

unsigned versionNumberHex(void)
{
    return VERSION_HEXNUM;
}

unsigned versionNumberDec(void)
{
    return VERSION_NUMBER;
}

int main(int argc, char** argv) 
{
    printf( "\nVersion String: %s\n", &versionstring().string[0] );
    printf( "Version Number dec: %u\n", versionNumberDec() );
    printf( "Version Number hex: %p\n", versionNumberHex() );
    return (int)VERSION_NUMBER;
}